stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: gradle:latest
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew test

services:
  - name: mongo:5.0
    alias: UserMongoFARO

build_image:
  stage: build
  image: gradle:latest
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew build

deploy:
  stage: deploy
  image: gradle:latest
  before_script:
    - chmod 600 $AWS_SECRET_ACCESS_KEY
    - chmod +x gradlew
    - ./gradlew build
  script:
    - scp -o StrictHostKeyChecking=no -i $AWS_SECRET_ACCESS_KEY build/UserServiceFARO-0.0.1-SNAPSHOT-runner.jar ubuntu@54.210.170.92:/home/ubuntu/UserService
    - scp -o StrictHostKeyChecking=no -i $AWS_SECRET_ACCESS_KEY docker-compose.yml ubuntu@54.210.170.92:/home/ubuntu/UserService
    - ssh -o StrictHostKeyChecking=no -i $AWS_SECRET_ACCESS_KEY ubuntu@54.210.170.92 "sudo docker kill mysbaimage; sudo docker kill mongodbimage; cd UserService; sudo docker compose up -d"